# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
